name: string_sims_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - mdanalysis
  - nodejs
  - numpy
  - pandas
  - pip
  - python=3.8.5
  - scipy
  - seaborn
  - tqdm
  - ipykernel
  - deeptime
  - pip:
    - nb_black
