name: string_sims
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - mdanalysis
  - nodejs
  - numpy
  - pandas
  - pip
  - python=3.8.5
  - scipy
  - seaborn
  - tqdm
  - ipykernel
  - ipympl
  - mamba
  - pyright
  - isort
  - flake8
  - flake8-docstrings
  - nglview
  - deeptime
  # - pyemma
  - pip:
    - nb_black
    - panedr
